apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: student-mgmt
spec:
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: student-mgmt/prod/db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: student-mgmt/prod/db
        property: password
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: student-mgmt/prod/db
        property: jdbc_url
    - secretKey: JWT_SECRET
      remoteRef:
        key: student-mgmt/prod/jwt
        property: secret
