apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: student-mgmt
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: student-mgmt/db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: student-mgmt/db
        property: password
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: student-mgmt/db
        property: jdbc_url
    - secretKey: JWT_SECRET
      remoteRef:
        key: student-mgmt/jwt
        property: secret
