apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: student-mgmt-dev
resources:
- ../../base
- sealed-secrets
images:
- name: student-mgmt/backend
  newName: 899259776537.dkr.ecr.ap-northeast-2.amazonaws.com/student-mgmt/backend
  newTag: 31dd6019e3041b623f8f3023863c6d14bb1c83d4
patches:
- path: ingress-patch.yaml
