apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: student-mgmt-dev
resources:
- ../../base
- sealed-secrets
images:
- name: student-mgmt/backend
  newName: 899259776537.dkr.ecr.ap-northeast-2.amazonaws.com/student-mgmt/backend
  newTag: 9b0d383f7dd62ba3710c80ac5c858c7794bb50e3
patches:
- path: ingress-patch.yaml
- path: cdc-patch.yaml
