apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: student-mgmt-dev
resources:
  - ../../base
  - sealed-secrets
images:
  - name: student-mgmt/backend
    newName: <ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/student-mgmt/backend
    newTag: latest
patches:
  - path: ingress-patch.yaml
