apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main
  namespace: student-mgmt
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "<ACM_CERT_ARN>"
    alb.ingress.kubernetes.io/group.name: student-mgmt-staging
    external-dns.alpha.kubernetes.io/hostname: "staging.<domain>"
